/** @format */

module.exports = {
	// The minimal baseline configuration goes here
	ignorePatterns: ["**/dist/**", "**/node_modules/**"],
	plugins: ["promise", "lodash"],
	extends: [
		"plugin:promise/recommended",
		"plugin:lodash/canonical",
		"eslint:recommended",
		"airbnb",
		"prettier",
	],

	rules: {
		quotes: ["warn", "double", { avoidEscape: true }],
		"no-await-in-loop": "warn",
		"no-console": ["warn", { allow: ["debug", "warn", "error"] }],
		"no-loss-of-precision": "error",
		"no-promise-executor-return": "error",
		"no-unreachable-loop": "error",
		"no-unsafe-optional-chaining": "error",
		"require-atomic-updates": "error",
		"array-callback-return": "error",
		"block-scoped-var": "error",
		"class-methods-use-this": "warn",
		complexity: "warn",
		"consistent-return": "error",
		"default-case": "warn",
		"default-case-last": "error",
		"default-param-last": "error",
		"grouped-accessor-pairs": "warn",
		"guard-for-in": "warn",
		"max-classes-per-file": ["warn", 3],
		"dot-notation": "warn",
		eqeqeq: "error",
		"no-alert": "error",
		"no-caller": "error",
		"no-constructor-return": "error",
		"no-div-regex": "warn",
		"no-eval": "error",
		"no-extend-native": "error",
		"no-extra-bind": "warn",
		"no-extra-label": "warn",
		"no-floating-decimal": "warn",
		"no-implicit-globals": "error",
		"no-implied-eval": "error",
		"no-invalid-this": "error",
		"no-iterator": "warn",
		"no-lone-blocks": "warn",
		"no-loop-func": "error",
		"no-magic-numbers": [
			"warn",
			{
				ignore: [0, 1, -1, 2],
				ignoreArrayIndexes: true,
				enforceConst: true,
				ignoreDefaultValues: true,
			},
		],
		"no-new-func": "error",
		"no-new-wrappers": "error",
		"no-nonoctal-decimal-escape": "error",
		"no-octal-escape": "error",
		"no-param-reassign": "warn",
		"no-proto": "error",
		"no-return-assign": "error",
		"no-return-await": "warn",
		"no-script-url": "error",
		"no-self-compare": "error",
		"no-sequences": "error",
		"no-throw-literal": "error",
		"no-unmodified-loop-condition": "warn",
		"no-unused-expressions": "warn",
		"no-useless-call": "warn",
		"no-useless-concat": "warn",
		"no-useless-return": "warn",
		"no-void": "error",
		"prefer-promise-reject-errors": "error",
		"prefer-regex-literals": "warn",
		radix: "error",
		"require-unicode-regexp": "warn",
		"vars-on-top": "error",
		"wrap-iife": "warn",
		yoda: "warn",
		"init-declarations": "warn",
		"no-label-var": "warn",
		"no-shadow": "error",
		"no-undefined": "warn",
		"no-use-before-define": "error",
		"prefer-object-spread": "warn",
		"prefer-exponentiation-operator": "warn",
		"wrap-regex": "warn",
		"no-confusing-arrow": "error",
		"no-duplicate-imports": "warn",
		"no-var": "warn",
		"prefer-const": "warn",
		"prefer-destructuring": "warn",
		"prefer-numeric-literals": "warn",
		"prefer-rest-params": "warn",
		"prefer-spread": "warn",
		"prefer-template": "warn",
		"sort-imports": "warn",
		"symbol-description": "warn",
		"no-underscore-dangle": "off",
		"import/prefer-default-export": "off",
		"no-tabs": "off",
		"iterators/generators": "off",
		"no-restricted-syntax": "off",
	},

	// The file-specific overrides of the minimal baseline configuration.
	// Note that _all_ matching overrides for a file are applied in order,
	// so later matching overrides will overwrite the earlier overrides.
	overrides: [
		{
			// Typescript overrides
			files: ["**/*.ts"],
			parser: "@typescript-eslint/parser",
			plugins: ["@typescript-eslint"],
			extends: [
				"eslint:recommended",
				"plugin:@typescript-eslint/recommended",
				"plugin:@typescript-eslint/recommended-requiring-type-checking",
				"airbnb-typescript",
				"prettier", // Make sure this is run last
			],
			rules: {
				"default-case": "off",
				quotes: "off",
				"@typescript-eslint/quotes": ["warn", "double", { avoidEscape: true }],
				"@typescript-eslint/restrict-template-expressions": "off",
			},
		},
	],
};
